### ISSUE TITLE
weakness break should use "toughness multiplier = 0.9"

### ISSUE THREAD

**Issue by nlrem** [simimpact/srsim#250]
when calculating **weakness break/stance break damage** in srsim (srsim_darwin_amd64 v0.0.4 if that's relevant), i noticed that it uses the value `toughness multiplier = 1.0`, rather than `0.9` (the value observed in-game).

here is the `HitEnd` of one such weakness break
<img width="588" alt="Screenshot 2023-12-22 at 22 14 08" src="https://github.com/simimpact/srsim/assets/154653426/175a44c6-8dcd-4636-a0bd-926c730006b8">

(here's the enemy stats from the corresponding `HitStart` for reference --- ignore the abnormally high hp, just using the testing dummy for some quick checks)
<img width="504" alt="Screenshot 2023-12-22 at 22 19 50" src="https://github.com/simimpact/srsim/assets/154653426/70b382cd-24b5-4a80-8f5f-b3710e2271fa">

**Comment by agentyoda** [comment]
#252 may fix this. If you want to link the config you used, I can test locally and see if that fixes the issue.

**Comment by agentyoda** [comment]
This should have been fixed with #252 so I'll close this task.
